import Navbar from "../Navbar/page"

export const metadata = {
    title: 'Blog app',
    description: 'Generated by ahbab',
  }
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body >
          <Navbar/>
          {children}</body>
      </html>
    )
  }